name: 'Release Bot'
description: 'Standard Pony Library and Application release functionality'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  git_user_name:
    description: 'Name to associate with commits.'
    required: true
  git_user_email:
    description: 'Email to associate with commits.'
    required: true
